spring.application.name=tutaller-api
server.port=${PORT:8080}

# Carga configuracion local privada si existe.
# Este archivo NO se sube a Git y se usa solo en desarrollo local.
spring.config.import=optional:file:./application-local.properties

# Configuracion publica/base del proyecto.
# Puede ser sobreescrita por variables de entorno o por application-local.properties.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tutaller_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Estas propiedades no son secretas, por eso viven en application.properties.
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
